export * from "./browser-launcher";
export * from "./config";
export * from "./image-extractor";
export * from "./universal-extractor";
export * from "./description-facts";
export * from "./brand-resolver";
export type { ExtractedProductData, ProductDataSource } from "./product-data-extractor";
export { extractProductGroupOptions, extractFromJsonLd } from "./product-data-extractor";
export type { ExtractionTrace } from "./scoring";
export type { StrategySource } from "./strategies/types";
export * from "./comparison-search";
export * from "./shopify-market-probe";
export { fetchShopifyShopMeta, stripShopifyLocalePrefix, type ShopifyShopMeta } from "./shopify-product-json";
export { normalizeUrl } from "./utils/url.util";
